users:
  upcoming_event: 5
colors: ["#AC725E",  "#D06B64", "#F83A22", "#FA573C", "#FF7537", "#FFAD46",
  "#42D692", "#16A765", "#B3DC6C", "#FBE983", "#FAD165", "#92E1C0"]
permissions: ["manage", "make_change", "see_detail", "hide_details"]
permissions_can_make_change: [1, 2]
event:
  format_date: "%Y-%m-%d"
  format_time: "%H:%M"
  format_datetime: "%Y-%m-%d %H:%M"
  format_date_basic: "%Y%m%d"
  repeat_data: ["su", "mo", "tu", "we", "th", "fr", "sa"]
repeat:
  repeat_type:
    daily: "daily"
    weekly: "weekly"
    monthly: "monthly"
    yearly: "yearly"
  repeat_every: 30
second_in_day: 86400
days: "days"
weeks: "weeks"
months: "months"
years:  "years"
seven: 7
thirty: 30
sync_params_true: "true"
response_status_Ok: 200
url: "localhost:3000/particular_calendars/"
minutes_in_day: 1440
chatwork_room_id: "51184775"
email: "https://www.googleapis.com/auth/userinfo.email"
calendar: "https://www.googleapis.com/auth/calendar"
notify_type:
  email: "email"
status_confirmed: "confirmed"
content_type: "application/json"
refresh_token_url: "https://accounts.google.com/o/oauth2/token"
